version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: docker-frontend
    command: npm run start
    ports:
      - 3000:3000
    restart: unless-stopped
    stdin_open: true
    tty: true
