version: "3"
services:
  api:
    build: ./api
    command: npm run start
    ports:
      - 80:8080
    environment:
      - PORT=8080
      - HOST=http://localhost
      - MONGO_URL=mongodb://mongo:27017/api
    links:
      - "mongo"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_api:/data/db
volumes:
  mongodb_api:

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   command: npm run start
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped
  #   stdin_open: true
  #   tty: true
